In [1]:
# data encoding --> converting categorical column to numeric value

In [2]:
# nominal/OHE
# label and ordinal encoding
# target guided ordinal encoding

In [3]:
# nominal hot encoding --> binary vectors for each category 
# example 
#  single ,married, in-a-relationship
# single >> 1 0 0
# married >> 0 1 0
# in-a-relationship >> 0 0 1

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [11]:
df = pd.DataFrame({'Status': ["Single", "Married","Single","Relationship" ,"Married","Single"]})
df

Status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [12]:
encoder = OneHotEncoder()
encoder

OneHotEncoder()

In [16]:
encoded = encoder.fit_transform(df[['Status']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [17]:
encoder.get_feature_names_out()

array(['Status_Married', 'Status_Relationship', 'Status_Single'],
      dtype=object)

In [20]:
encoder_df= pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [21]:
# new data >> single
encoder.transform([['Single']]).toarray()

C:\Users\harsh\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [25]:
final_df = pd.concat([df,encoder_df ], axis=1)

In [26]:
final_df 

Status        Status  Status_Married  Status_Relationship  \
0        Single        Single             0.0                  0.0   
1       Married       Married             1.0                  0.0   
2        Single        Single             0.0                  0.0   
3  Relationship  Relationship             0.0                  1.0   
4       Married       Married             1.0                  0.0   
5        Single        Single             0.0                  0.0   

   Status_Single  
0            1.0  
1            0.0  
2            1.0  
3            0.0  
4            0.0  
5            1.0

In [27]:
final_df.drop(['Status','Status_Married'], axis=1, inplace=True)

In [29]:
final_df

Status_Relationship  Status_Single
0                  0.0            1.0
1                  0.0            0.0
2                  0.0            1.0
3                  1.0            0.0
4                  0.0            0.0
5                  0.0            1.0

In [32]:
pd.get_dummies(df[["Status"]])

Status_Married  Status_Relationship  Status_Single
0           False                False           True
1            True                False          False
2           False                False           True
3           False                 True          False
4            True                False          False
5           False                False           True

In [33]:
#label encoding >> assign unique label to the categories
df

Status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
label_encoder = LabelEncoder()

In [37]:
label_encoder.fit_transform(df[['Status']])

C:\Users\harsh\AppData\Roaming\Python\Python311\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 2, 1, 0, 2])

In [38]:
df

Status
0        Single
1       Married
2        Single
3  Relationship
4       Married
5        Single

In [39]:
#ordinal encoding
#high school >>1
#gaduate >> 2
#pg >> 3
#phd>> 4

In [40]:
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({"qualification": ["HS", "PG","GR", "HS", "PhD", "HS", "PG"]})

In [41]:
df

qualification
0            HS
1            PG
2            GR
3            HS
4           PhD
5            HS
6            PG

In [42]:
encoder = OrdinalEncoder(categories = [["HS", "GR", "PG", "PhD"]])

In [43]:
encoder.fit_transform(df[['qualification']])

array([[0.],
       [2.],
       [1.],
       [0.],
       [3.],
       [0.],
       [2.]])

In [44]:
df

qualification
0            HS
1            PG
2            GR
3            HS
4           PhD
5            HS
6            PG

In [45]:
#Top 5/top 10>> atleast 70 or 80 precnt of the categorical column captured

df.qualification.value_counts()

qualification
HS     3
PG     2
GR     1
PhD    1
Name: count, dtype: int64

In [46]:
#target guided ordinal encoding
#relation with target variable
#A lot of unique categories
#replace with mean and and median

In [47]:
df = pd.DataFrame({'time': ['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 120, 40, 150, 160, 130,  40, 150, 160]})

In [48]:
df

time  total_bill
0      lunch         120
1  breakfast         120
2     dinner          40
3      lunch         150
4  breakfast         160
5     dinner         130
6      lunch          40
7  breakfast         150
8     dinner         160

In [49]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()


In [50]:
mean_price

{'breakfast': 143.33333333333334, 'dinner': 110.0, 'lunch': 103.33333333333333}

In [51]:
df['time_target_encoded'] = df['time'].map(mean_price)

In [52]:
df

time  total_bill  time_target_encoded
0      lunch         120           103.333333
1  breakfast         120           143.333333
2     dinner          40           110.000000
3      lunch         150           103.333333
4  breakfast         160           143.333333
5     dinner         130           110.000000
6      lunch          40           103.333333
7  breakfast         150           143.333333
8     dinner         160           110.000000